version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-container
    volumes:
      - newpgdata:/var/lib/postgresql/data
      # Mount the directory containing the SQL file into the container
      - ./database_snapshot.sql:/docker-entrypoint-initdb.d/database_snapshot.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword

  web:
    build: .
    container_name: django-container
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1

volumes:
  newpgdata:
