# Generated by Django 4.2.13 on 2024-05-30 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_friendrequest_status_alter_friendrequest_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 20, 51, 46, 242942)),
        ),
    ]
