# Generated by Django 4.2.13 on 2024-05-30 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_friendrequest_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 22, 18, 46, 129668)),
        ),
    ]
