# Generated by Django 4.2.13 on 2024-05-31 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_friendrequest_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 31, 7, 29, 59, 735147)),
        ),
    ]
